//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLoadTest.VuGenAddInManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLoadTest.VuGenAddInManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AddInManager_About {
            get {
                return ResourceManager.GetString("AddInManager_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel installation.
        /// </summary>
        public static string AddInManager_ActionCancelInstallation {
            get {
                return ResourceManager.GetString("AddInManager_ActionCancelInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel uninstallation.
        /// </summary>
        public static string AddInManager_ActionCancelUninstallation {
            get {
                return ResourceManager.GetString("AddInManager_ActionCancelUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel update.
        /// </summary>
        public static string AddInManager_ActionCancelUpdate {
            get {
                return ResourceManager.GetString("AddInManager_ActionCancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string AddInManager_ActionDisable {
            get {
                return ResourceManager.GetString("AddInManager_ActionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string AddInManager_ActionEnable {
            get {
                return ResourceManager.GetString("AddInManager_ActionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string AddInManager_ActionInstall {
            get {
                return ResourceManager.GetString("AddInManager_ActionInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string AddInManager_ActionUninstall {
            get {
                return ResourceManager.GetString("AddInManager_ActionUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string AddInManager_ActionUpdate {
            get {
                return ResourceManager.GetString("AddInManager_ActionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dependency for this AddIn was not found. Install it to enable this add-in..
        /// </summary>
        public static string AddInManager_AddInDependencyFailed {
            get {
                return ResourceManager.GetString("AddInManager_AddInDependencyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AddInManager_AddInDisabled {
            get {
                return ResourceManager.GetString("AddInManager_AddInDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in will be enabled after restarting HP Virtual User Generator.
        /// </summary>
        public static string AddInManager_AddInEnabled {
            get {
                return ResourceManager.GetString("AddInManager_AddInEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in will be installed after restarting HP Virtual User Generator.
        /// </summary>
        public static string AddInManager_AddInInstalled {
            get {
                return ResourceManager.GetString("AddInManager_AddInInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-in is installed twice. Please uninstall one copy..
        /// </summary>
        public static string AddInManager_AddInInstalledTwice {
            get {
                return ResourceManager.GetString("AddInManager_AddInInstalledTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add-in must have an &lt;Identity&gt; for use with the AddIn-Manager..
        /// </summary>
        public static string AddInManager_AddInMustHaveIdentity {
            get {
                return ResourceManager.GetString("AddInManager_AddInMustHaveIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in will be removed after restarting HP Virtual User Generator.
        /// </summary>
        public static string AddInManager_AddInRemoved {
            get {
                return ResourceManager.GetString("AddInManager_AddInRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in will be updated after restarting HP Virtual User Generator.
        /// </summary>
        public static string AddInManager_AddInUpdated {
            get {
                return ResourceManager.GetString("AddInManager_AddInUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in will be disabled after restarting HP Virtual User Generator.
        /// </summary>
        public static string AddInManager_AddInWillBeDisabled {
            get {
                return ResourceManager.GetString("AddInManager_AddInWillBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot disable the AddInManager because you need it to re-enable AddIns!.
        /// </summary>
        public static string AddInManager_CannotDisableAddInManager {
            get {
                return ResourceManager.GetString("AddInManager_CannotDisableAddInManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot install add-ins inside the HP Virtual User Generator directory, they will be picked up as pre-installed add-ins automatically..
        /// </summary>
        public static string AddInManager_CannotInstallIntoApplicationDirectory {
            get {
                return ResourceManager.GetString("AddInManager_CannotInstallIntoApplicationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AddInManager_CloseButtonText {
            get {
                return ResourceManager.GetString("AddInManager_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborts the installation of the selected AddIn(s)..
        /// </summary>
        public static string AddInManager_DescriptionCancelInstall {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionCancelInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborts the uninstallation of the selected AddIn(s)..
        /// </summary>
        public static string AddInManager_DescriptionCancelUninstallation {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionCancelUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborts the update of the selected AddIn(s)..
        /// </summary>
        public static string AddInManager_DescriptionCancelUpdate {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionCancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the selected AddIn(s)..
        /// </summary>
        public static string AddInManager_DescriptionDisable {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the selected AddIn(s)..
        /// </summary>
        public static string AddInManager_DescriptionEnable {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection is inconsistent, please select only AddIns with the same status..
        /// </summary>
        public static string AddInManager_DescriptionInconsistentSelection {
            get {
                return ResourceManager.GetString("AddInManager_DescriptionInconsistentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIn Installation Package.
        /// </summary>
        public static string AddInManager_FileAssociation {
            get {
                return ResourceManager.GetString("AddInManager_FileAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VuGen add-ins|*.vugenaddin|All files|*.*.
        /// </summary>
        public static string AddInManager_FileFilter {
            get {
                return ResourceManager.GetString("AddInManager_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install add-in.
        /// </summary>
        public static string AddInManager_InstallButton {
            get {
                return ResourceManager.GetString("AddInManager_InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any AddIns installed.
        ///Download an AddIn from the Internet, then click &apos;Install AddIn&apos; and choose the downloaded file to install it..
        /// </summary>
        public static string AddInManager_NoAddInsInstalled {
            get {
                return ResourceManager.GetString("AddInManager_NoAddInsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Website.
        /// </summary>
        public static string AddInManager_OpenWebsite {
            get {
                return ResourceManager.GetString("AddInManager_OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string AddInManager_Options {
            get {
                return ResourceManager.GetString("AddInManager_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIns are required by:.
        /// </summary>
        public static string AddInManager_RequiredBy {
            get {
                return ResourceManager.GetString("AddInManager_RequiredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required dependencies:.
        /// </summary>
        public static string AddInManager_RequiredDependencies {
            get {
                return ResourceManager.GetString("AddInManager_RequiredDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preinstalled AddIns.
        /// </summary>
        public static string AddInManager_ShowPreinstalledAddIns {
            get {
                return ResourceManager.GetString("AddInManager_ShowPreinstalledAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIn Manager.
        /// </summary>
        public static string AddInManager_Title {
            get {
                return ResourceManager.GetString("AddInManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file format:.
        /// </summary>
        public static string AddInManager_UnknownFileFormat {
            get {
                return ResourceManager.GetString("AddInManager_UnknownFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install from archive....
        /// </summary>
        public static string AddInManager2_AddInsView_InstallFromArchive {
            get {
                return ResourceManager.GetString("AddInManager2_AddInsView_InstallFromArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository:.
        /// </summary>
        public static string AddInManager2_AddInsView_Repository {
            get {
                return ResourceManager.GetString("AddInManager2_AddInsView_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string AddInManager2_AddInsView_Search {
            get {
                return ResourceManager.GetString("AddInManager2_AddInsView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preinstalled AddIns.
        /// </summary>
        public static string AddInManager2_AddInsView_ShowPreinstalledAddIns {
            get {
                return ResourceManager.GetString("AddInManager2_AddInsView_ShowPreinstalledAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prereleases.
        /// </summary>
        public static string AddInManager2_AddInsView_ShowPrereleaseAddIns {
            get {
                return ResourceManager.GetString("AddInManager2_AddInsView_ShowPrereleaseAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot uninstall the AddInManager because you need it to re-install AddIns!.
        /// </summary>
        public static string AddInManager2_CannotRemoveAddInManager {
            get {
                return ResourceManager.GetString("AddInManager2_CannotRemoveAddInManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Virtual User Generator AddIn Repository.
        /// </summary>
        public static string AddInManager2_DefaultRepository {
            get {
                return ResourceManager.GetString("AddInManager2_DefaultRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string AddInManager2_Details_CreatedBy {
            get {
                return ResourceManager.GetString("AddInManager2_Details_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies:.
        /// </summary>
        public static string AddInManager2_Details_Dependencies {
            get {
                return ResourceManager.GetString("AddInManager2_Details_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads:.
        /// </summary>
        public static string AddInManager2_Details_DownloadCount {
            get {
                return ResourceManager.GetString("AddInManager2_Details_DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string AddInManager2_Details_FileName {
            get {
                return ResourceManager.GetString("AddInManager2_Details_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version:.
        /// </summary>
        public static string AddInManager2_Details_InstalledVersion {
            get {
                return ResourceManager.GetString("AddInManager2_Details_InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        public static string AddInManager2_Details_LastUpdated {
            get {
                return ResourceManager.GetString("AddInManager2_Details_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string AddInManager2_Details_MoreInformation {
            get {
                return ResourceManager.GetString("AddInManager2_Details_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        public static string AddInManager2_Details_NewVersion {
            get {
                return ResourceManager.GetString("AddInManager2_Details_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string AddInManager2_Details_Rating {
            get {
                return ResourceManager.GetString("AddInManager2_Details_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report abuse.
        /// </summary>
        public static string AddInManager2_Details_ReportAbuse {
            get {
                return ResourceManager.GetString("AddInManager2_Details_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AddInManager2_Details_Version {
            get {
                return ResourceManager.GetString("AddInManager2_Details_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License Terms.
        /// </summary>
        public static string AddInManager2_Details_ViewLicenseTerms {
            get {
                return ResourceManager.GetString("AddInManager2_Details_ViewLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following installed AddIns are depending on &quot;{0}&quot;:
        ///
        ///{1}
        ///
        ///They will stop working after disabling this AddIn! Are you sure you want to continue?.
        /// </summary>
        public static string AddInManager2_DisableDependentWarning {
            get {
                return ResourceManager.GetString("AddInManager2_DisableDependentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &quot;{0}&quot; needs at least one additional package:
        ///
        ///{1}
        ///
        ///The application will try to download and install them, as well. Do you want to continue?.
        /// </summary>
        public static string AddInManager2_InstallDependentMessage {
            get {
                return ResourceManager.GetString("AddInManager2_InstallDependentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected package doesn&apos;t contain a valid HP Virtual User Generator AddIn..
        /// </summary>
        public static string AddInManager2_InvalidPackage {
            get {
                return ResourceManager.GetString("AddInManager2_InvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I &amp;Accept.
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_AcceptButton {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I &amp;Decline.
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_DeclineButton {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_DeclineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;I Accept&quot; you agree to the license terms for the package listed above.
        ///If you do not agree to the license terms click &quot;I Decline&quot;..
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_Explanation_Package {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_Explanation_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;I Accept&quot; you agree to the license terms for the packages listed above.
        ///If you do not agree to the license terms click &quot;I Decline&quot;..
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_Explanation_Packages {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_Explanation_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following package requires a click-to-accept license:.
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_Introduction_Package {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_Introduction_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following packages require a click-to-accept license:.
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_Introduction_Packages {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_Introduction_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreements.
        /// </summary>
        public static string AddInManager2_LicenseAcceptance_Title {
            get {
                return ResourceManager.GetString("AddInManager2_LicenseAcceptance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddInManager2_OptionPanel_Add {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        public static string AddInManager2_OptionPanel_AutoCheckForUpdates {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_AutoCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string AddInManager2_OptionPanel_MoveDown {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string AddInManager2_OptionPanel_MoveUp {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AddInManager2_OptionPanel_Name {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string AddInManager2_OptionPanel_Remove {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string AddInManager2_OptionPanel_Source {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIns.
        /// </summary>
        public static string AddInManager2_OptionPanel_Tree_AddIns {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Tree_AddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string AddInManager2_OptionPanel_Tree_General {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Tree_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string AddInManager2_OptionPanel_Tree_Repositories {
            get {
                return ResourceManager.GetString("AddInManager2_OptionPanel_Tree_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following installed AddIns are depending on &quot;{0}&quot;:
        ///
        ///{1}
        ///
        ///They will stop working after removing this AddIn! Are you sure you want to continue?.
        /// </summary>
        public static string AddInManager2_RemoveDependentWarning {
            get {
                return ResourceManager.GetString("AddInManager2_RemoveDependentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VuGen AddIns|*.vugenaddin|All files|*.*.
        /// </summary>
        public static string AddInManager2_SDAddInFileFilter {
            get {
                return ResourceManager.GetString("AddInManager2_SDAddInFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to see the updates..
        /// </summary>
        public static string AddInManager2_UpdateNotifier_BubbleText {
            get {
                return ResourceManager.GetString("AddInManager2_UpdateNotifier_BubbleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates for HP Virtual User Generator are available.
        /// </summary>
        public static string AddInManager2_UpdateNotifier_BubbleTitle {
            get {
                return ResourceManager.GetString("AddInManager2_UpdateNotifier_BubbleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string AddInManager2_Views_Available {
            get {
                return ResourceManager.GetString("AddInManager2_Views_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string AddInManager2_Views_Installed {
            get {
                return ResourceManager.GetString("AddInManager2_Views_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string AddInManager2_Views_Updates {
            get {
                return ResourceManager.GetString("AddInManager2_Views_Updates", resourceCulture);
            }
        }
    }
}
